### ISSUE TITLE
C/C++ preprocessor definitions

### ISSUE THREAD

**Issue by christian-herber-nxp** [riscv-non-isa/riscv-toolchain-conventions#57]
`__riscv_mul: defined when targeting the 'M' ISA extension.`

I think it is safe to change this to targeting the 'M' or "Zmul' ISA extension.

`__riscv_compressed: defined when targeting the 'C' ISA extension.`

How is this expected to behave when not the full C, but elements of Zc are implemented?

**Comment by cmuellner** [comment]
It is safe from a "functionality included in an extension" view.
That does not mean that it still cannot break builds.

I'm okay with this such a change if LLVM and GCC maintainers accept patches that implement this change.

**Comment by cmuellner** [comment]
We've briefly discussed this twice in Toolchain SIG calls.
Changes that potentially break a build have no realistic chance of landing in GCC/LLVM.

Therefore, closing this issue.
